spring:
  profiles:
    active: dev
  config:
    import:
    - optional:configserver:http://localhost:8888
    - vault://secret/unit-of-measure-service/dev
  cloud:
    vault:
      application-name: ${spring.application.name}
      uri: http://localhost:8200
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
  application:
    name: unit-of-measure-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unit_of_measure_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0 # Use 0 to let Spring Boot assign a random available port at startup (useful for testing, avoiding port conflicts, or running multiple instances)
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # Unique identifier for this service instance in Eureka
    lease-expiration-duration-in-seconds: 90 # Time (seconds) Eureka waits before removing an instance if no heartbeat is received
    lease-renewal-interval-in-seconds: 30 # Interval (seconds) for sending heartbeats to Eureka to renew registration
    prefer-ip-address: true # Register service using IP address instead of hostname
    metadata-map:
      version: 1.0.0 # Custom metadata: service version
      environment: production # Custom metadata: environment (e.g., production, staging)
      region: us-east # Custom metadata: region/location of the service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL for service registration and discovery
