spring:
  profiles:
    active: dev
  config:
    import:
    - optional:configserver:http://localhost:8888
    - vault://secret/unit-of-measure-service/dev
  cloud:
    vault:
      application-name: ${spring.application.name}
      uri: http://localhost:8200
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
  application:
    name: unit-of-measure-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unit_of_measure_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    metadata-map:
      version: 1.0.0
      environment: production
      region: us-east
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
