# Spring Boot test profile configuration
spring:
  datasource:
    # H2 in-memory database for isolated, fast tests
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Create a schema for each test run
    show-sql: true          # Show SQL in logs for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Override PostgreSQL dialect
#        format_sql: true    # Pretty print SQL
#        use_sql_comments: true
  h2:
    console:
      enabled: true         # Enable H2 web console
      path: /h2-console
  sql:
    init:
      mode: always          # Always run schema/data scripts if present
      platform: h2
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE