spring:
  application:
    name: unit-of-measure-service
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0 # Use 0 to let Spring Boot assign a random available port at startup (useful for testing, avoiding port conflicts, or running multiple instances)
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # Unique identifier for this service instance in Eureka
    lease-expiration-duration-in-seconds: 90 # Time (seconds) Eureka waits before removing an instance if no heartbeat is received
    lease-renewal-interval-in-seconds: 30 # Interval (seconds) for sending heartbeats to Eureka to renew registration
    prefer-ip-address: true # Register service using IP address instead of hostname
    metadata-map:
      version: 1.0.0 # Custom metadata: service version
      environment: production # Custom metadata: environment (e.g., production, staging)
      region: us-east # Custom metadata: region/location of the service
  client:
    service-url:
      defaultZone: ${EUREKA_URL:} # Eureka server URL for service registration and discovery
