server:
  port: 0
spring:
  application:
    name: unit-of-measure-service
  config:
    import:
      - optional:configserver:http://localhost:8888
      - vault://secret/unit-of-measure-service/dev
  cloud:
    vault:
      application-name: ${spring.application.name}
      uri: http://localhost:8200
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
  datasource:
    url: jdbc:postgresql://localhost:5432/unit_of_measure_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      version: 1.0.0
      environment: development
      region: us-east
    prefer-ip-address: true